spring:
  datasource:
    url: jdbc:h2:mem:localdb # inmemory db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true # default console path = /h2-console
